kind: Kustomization
resources:
  - deployment.yaml
secretGenerator:
  - name: mysqlsecret
    literals:
      - DB_USER="dbadmin"
      - DB_PASSWORD="passit"
configMapGenerator:
  - name: databaseinfo
    literals:
      - DB_DATABASE="itemsx"