apiVersion: apps/v1
kind: Deployment
metadata:
  annotations:
    kubectl.kubernetes.io/last-applied-configuration: |
      {"kind":"Deployment","apiVersion":"apps/v1","metadata":{"name":"samplehttpd","creationTimestamp":null,"labels":{"app":"samplehttpd"}},"spec":{"replicas":1,"selector":{"matchLabels":{"app":"samplehttpd"}},"template":{"metadata":{"creationTimestamp":null,"labels":{"app":"samplehttpd"}},"spec":{"containers":[{"name":"httpd-24","image":"registry.redhat.io/ubi9/httpd-24:9.6-1745584807","resources":{}}]}},"strategy":{}},"status":{}}
  creationTimestamp: "2025-07-07T08:45:57Z"
  generation: 1
  labels:
    app: samplehttpd
  name: samplehttpd
  namespace: declar-ex
spec:
  progressDeadlineSeconds: 600
  replicas: 3
  revisionHistoryLimit: 10
  selector:
    matchLabels:
      app: samplehttpd
  strategy:
    rollingUpdate:
      maxSurge: 25%
      maxUnavailable: 25%
    type: RollingUpdate
  template:
    metadata:
      creationTimestamp: null
      labels:
        app: samplehttpd
    spec:
      containers:
      - image: registry.redhat.io/ubi9/httpd-24:latest
        imagePullPolicy: IfNotPresent
        name: httpd-24
        resources: {}
        terminationMessagePath: /dev/termination-log
        terminationMessagePolicy: File
      dnsPolicy: ClusterFirst
      restartPolicy: Always
      schedulerName: default-scheduler
      securityContext: {}
      terminationGracePeriodSeconds: 30
status: {}
