kind: Kustomization
namespace: test-apps
patches:
  - patch: |-
      - op: replace
        path: /metadata/name
        value: frontend-test
    options:
      allowNameChange: true
    target:
      kind: Deployment
      name: httpd24-app
  - patch: |-
      - op: replace
        path: /spec/replicas
        value: 3
    target:
      kind: Deployment
      name: httpd24-app

resources:
  - ../../base

# If the value ends with whitespace, like a newline, YAML will preserve it.
# To strip the character, use the strip operator. |-