kind: Kustomization
namespace: sampleapp
resources:
  - ../../base
secretGenerator:
  - name: mysqlsecret
    behavior: replace
    literals:
      - DB_USER="testdbadmin"
      - DB_PASSWORD="testpassit"
configMapGenerator:
  - name: databaseinfo
    behavior: replace
    literals:
      - DB_DATABASE=itemx